### ISSUE TITLE
Works but we see some gaps...

### ISSUE THREAD

**Issue by solunetspain** [Zimbra-Community/printpatch-zimlet#2] opened 2016-05-03 16:13 UTC
Hi, thanks for the zimlet. :-)
It works fine if print only a message but we see the following gaps:
- If messages are organized by conversation only prints the first
- Cannots elect multiple messages and print them 
- You can't print messages that are in shared folders from other users.
  It would be great to add these features.
  Thank you

**Comment by ghost** [comment] 2016-05-07 05:28
Hello and thanks for commenting, 

@jorgedlcruz would you think this is something Hoteles Globales is interested in too? And Jorge can you see and push internally at Zimbra at getting the bug https://bugzilla.zimbra.com/show_bug.cgi?id=95856 fixed in 8.8 so we do not need this zimlet?

@solunetspain if I have time I will look into some of your reported issues and fix some of them.

**Comment by jorgedlcruz** [comment] 2016-05-07 09:42
@barrydegraaff Hoteles Globales is a Customer of Solunet :) It will be great if you can fix it, when you have spare time :)

**Comment by ghost** [comment] 2016-05-07 10:30
Here it prints conversations without problems, maybe could you export the messages (conversations) that do not print, so I can see what the problem is. @jorgedlcruz maybe you can assist making a tar.gz export? Thanks!

![2016-05-07-122600_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4353213/15091641/4de51198-144f-11e6-9bb0-0c0535b58601.png)
![2016-05-07-122619_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4353213/15091642/505ff4f6-144f-11e6-8faa-9da1e30ed765.png)

**Comment by ghost** [comment] 2016-05-07 10:51
I released a new version 0.5, this version should also print from shared mailboxes. Please test and keep the old version around, just in case you find bugs in the new version, Barry

**Comment by ghost** [comment] 2016-05-07 15:07
I have a new much better solution, it is a patch on the native functionality.

*\* the below is ONLY for 8.6 version *\* if you use a different Zimbra let me know, test before prod and all that, use for your own risk.

To install, first remove the patch zimlet (as root):

```
 rm -Rf /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_printpatch
 cp /opt/zimbra/jetty/webapps/zimbra/WEB-INF/tags/message/messagePrintView.tag /opt/zimbra/jetty/webapps/zimbra/WEB-INF/tags/message/messagePrintView.tag-orig
 wget https://raw.githubusercontent.com/Zimbra-Community/printpatch-zimlet/master/messagePrintView.tag -O /opt/zimbra/jetty/webapps/zimbra/WEB-INF/tags/message/messagePrintView.tag
```

Then as zimbra: zmmailboxdctl restart

You should now be able to print w/o attachments being displayed. Please test! So I can remove the zimlet.

**Comment by ghost** [comment] 2016-05-07 15:08
This should fix this issue

**Closed as completed by ghost** 2016-05-07 15:08 UTC

**Comment by solunetspain** [comment] 2016-05-08 06:34
Hi Barry, thanks for the update.
Yes, Hoteles Globales is an about 400 mailboxes large hotel's Enterprise in Spain. (www.hotelesglobales.comhttp://www.hotelesglobales.com)
They asked me about the print question.
We will test and give feedback in a hort
Thanks for the job
Best regards

---

[cid:image001.gif@01D1A904.6A481FD0]

Javier García Alarcón
SOLUNET - Soluciones Internet S.L.
Fernando Moliné 40
50171 La Puebla de Alfindén, Zaragoza

## Tf.: 902 10 90 07  Fax: 976 45 55 69

Si Vd. va a imprimir este mensaje, piense primero si es absolutamente necesario. Economizar papel tinta y energía es proteger el medio ambiente
If you're going to print this message, please, think about it. Be careful with the environment.

Este mensaje y sus archivos adjuntos van dirigidos exclusivamente a su destinatario, pudiendo contener información confidencial sometida a secreto profesional. No está permitida su reproducción o distribución sin la autorización expresa de SOLUCIONES INTERNET S.L. Si Vd. no es el destinatario final, por favor elimínelo e infórmenos por esta vía.
                De acuerdo con lo establecido por la Ley Orgánica 15/1999 de 13 de Diciembre, de Protección de Datos de Carácter Personal (LOPD), le informamos que su datos están incorporados en fichero del que es titular SOLUCIONES INTERNET S.L., con la finalidad de realizar la gestión administrativa, contable y fiscal, así como enviarle comunicaciones comerciales sobre nuestros productos y/o servicios.
                Asimismo, le informamos de la posibilidad de ejercer los derechos de acceso, rectificación, cancelación y oposición de sus datos en el domicilio fiscal de SOLUCIONES INTERNET, S.L., sito en c/ Fernando Moliné nº 40 local, 50171 La Puebla de Alfindén (Zaragoza).
                Si Vd. no desea recibir nuestra información, póngase en contacto con nosotros enviado un correo electrónico a la siguiente dirección: facturacion@solunet.esmailto:facturacion@solunet.es

De: Barry de Graaff [mailto:notifications@github.com]
Enviado el: sábado, 07 de mayo de 2016 17:08
Para: Zimbra-Community/printpatch-zimlet
CC: Javier García Alarcón; Mention
Asunto: Re: [Zimbra-Community/printpatch-zimlet] Works but we see some gaps... (#2)

I have a new much better solution, it is a patch on the native functionality.

*\* the below is ONLY for 8.6 version *\* if you use a different Zimbra let me know, test before prod and all that, use for your own risk.

To install, first remove the patch zimlet (as root):

 rm -Rf /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_printpatch

 cp /opt/zimbra/jetty/webapps/zimbra/WEB-INF/tags/message/messagePrintView.tag /opt/zimbra/jetty/webapps/zimbra/WEB-INF/tags/message/messagePrintView.tag-orig

 wget https://raw.githubusercontent.com/Zimbra-Community/printpatch-zimlet/master/messagePrintView.tag -O /opt/zimbra/jetty/webapps/zimbra/WEB-INF/tags/message/messagePrintView.tag

Then as zimbra: zmmailboxdctl restart

You should now be able to print w/o attachments being displayed. Please test! So I can remove the zimlet.

**Comment by ghost** [comment] 2016-05-13 10:49
Added 
https://bugzilla.zimbra.com/show_bug.cgi?id=104927
